user:
  name: 
  location: Bengaluru
db: ./voiceassistant.db
assistant:
  name: thomas
music: 
application:
  intellij: 
email:
  server: smtp.gmail.com
  sender_username: 
  sender_password: 
  reciever_name: 
  reciever_mail: 
reminders:
  lunch: "14:00:00"
  dinner: "21:18:00"
  tea : "17:28:00"
  friend : "22:47:00"
